# Generated by Django 5.1.6 on 2025-02-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_date_added'),
        ('store', '0002_alter_product_created_data_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItrm',
            new_name='CartItem',
        ),
    ]
