# Generated by Django 5.1.6 on 2025-03-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_cartitrm_cartitem'),
        ('store', '0004_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variationa',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
