# Generated by Django 5.1.6 on 2025-03-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitem_variationa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variationa',
            new_name='variations',
        ),
    ]
